  [[main]]
  name = "Início"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Projetos"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Sobre mim"
  weight = 400
  identifier = "about"
  url = "/about/"

 
  [[main]]
  name = "Contate-me"
  weight = 600
  identifier = "contact"
  url = "/contact/"

 